name: Fairland
favicon: null
layout_spectrum: 0.50469
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e4bd3e'
    - '#0c598d'
    - '#0c0c0c'
    - '#877329'
  brandStrength: 0
  lightness: 0
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
