name: Fairland
favicon: null
layout_spectrum: 0.99139
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5bd3e'
    - '#0c598e'
    - '#0c0c0c'
    - '#867229'
    - '#443b19'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
